### ISSUE TITLE
Login page 

### ISSUE THREAD

**Issue by AksheKumar** [milyasyousuf/Ecommerce_SQA_Project#1]
login credentials aren't being checked, if they are empty on pressing login button.

**Comment by zainmustafa** [comment]
I will look into it.

**Comment by milyasyousuf** [comment]
@zainmustafa  awesome

**Comment by zainmustafa** [comment]
When clicked user is now routed back to login page.

**Comment by zainmustafa** [comment]
@AksheKumar validations are applied please review and verify.
