### ISSUE TITLE
Pin Code taking more then 5 digit input and registering 

### ISSUE THREAD

**Issue by rizisuper** [milyasyousuf/Ecommerce_SQA_Project#12]
It's only taking number which is fine but it also takes input of more then 5 digit and it even registers that data

![screenshot_13](https://user-images.githubusercontent.com/33057188/34466362-2cc44414-eef2-11e7-8217-fa2fabd63adf.png)

**Comment by zainmustafa** [comment]
Going through this [thread](https://stackoverflow.com/questions/325041/i-need-to-store-postal-codes-in-a-database-how-big-should-the-column-be). US has 9 digits, Canada 7 and pakistan 5. Now the range is fixed from 5-9. You can verify.
